### ISSUE TITLE
[BUG] Black screen after Exiting Spectate

### ISSUE THREAD

**Issue by VIRUXE** [tabarra/txAdmin#548]
**txAdmin/FXServer versions:**
![image](https://user-images.githubusercontent.com/1616657/147419434-c27b475f-d7c2-410f-a5f3-6b73cb8a068f.png)
  
**Describe the bug**
You spectate someone, then exit and the screen stays black with the loading icon at the bottom.

**To Reproduce**
Spectate someone
Exit to normal mode

**Expected behavior**
Exit to normal mode

**Screenshots**
![image](https://user-images.githubusercontent.com/1616657/147419427-b6e44c75-728d-40a8-bc16-0f2f79183829.png)

**Comment by GeerdoDaGr8** [comment]
I have had the same issue a lot as well.

**Comment by TasoOneAsia** [comment]
Can you guys provide some reproduction steps to achieve this? Until then its a little hard to track down the issue as it isn't appearing while testing.

**Comment by VIRUXE** [comment]
I'll do some further testing on the latest build and report back. Haven't used this in a while.

**Comment by SlugTeamSix** [comment]
Issue is still present in 4.13.1 atop 5367, I am attempting to get some prints going to figure out where the problem hits. Seems to happen pretty randomly when spectating players. Sometimes on the first spec, sometimes, the second, sometimes when it's too fast, sometimes when you sit in a spec for a long time. Will update if I can clear it up.

**Comment by TasoOneAsia** [comment]
This hopefully should be resolved with #591, but will need to do some final testing.

**Comment by Neo1030** [comment]
Hi
I have the same problem already
i run with the latest version
Did you find a solution?

**Comment by VIRUXE** [comment]
@Neo1030 Not sure. I stopped playing FiveM.

**Comment by Tinky124** [comment]
@Neo1030 Still bug

**Comment by Rqver** [comment]
Can confirm that this issue still occurs when player counts are around 30-60.

**Comment by tabarra** [comment]
Probably solved, an update will be released in the next month to fix it.

**Comment by BigSmashGG** [comment]
> Probably solved, an update will be released in the next month to fix it.

I am having this issue currently. 
 v4.18.1 atop FXServer 6033 is the current txadmin running. any fix or info on this?

**Comment by TasoOneAsia** [comment]
> This hopefully should be resolved with https://github.com/tabarra/txAdmin/pull/591, but will need to do some final testing.

See this.

**Comment by BrazyUK** [comment]
Still an issue

**Comment by ElyzaEvans** [comment]
Still an issue. Happens to me  a few times a day.
